import React, { useState, useEffect } from "react";
import json from './data.json'
import Select from 'react-select';
import makeAnimated from 'react-select/animated';
import 'bootstrap/dist/css/bootstrap.min.css';
import Box from '@mui/material/Box';
import './AddEvents.css';
import {NotificationContainer, NotificationManager} from 'react-notifications';
import CreatableSelect from 'react-select/creatable';

const animatedComponents = makeAnimated();
const Countries = [
  {label:'All', value: 1},
  {label:'Abergavenny',value: 683},
  {label:'Abingdon',value: 211},
  {label:'Acton',value: 502},
  {label:'Addlestone',value: 542},
  {label:'Admiral Park (Guernsey)',value: 335},
  {label:'Alcester',value: 474},
  {label:'Alderley Edge',value: 560},
  {label:'Alderley Old',value: 602},
  {label:'Allington Park',value: 137},
  {label:'Alton',value: 329},
  {label:'Altrincham',value: 494},
  {label:'Amersham',value: 578},
  {label:'Ampthill',value: 722},
  {label:'Andover',value: 168},
  {label:'Ashbourne',value: 316},
  {label:'Ashford',value: 705},
  {label:'Aylesbury',value: 625},
  {label:'Bagshot Road',value: 738},
  {label:'Bagshot',value: 514},
  {label:'Balham',value: 719},
  {label:'Banbury',value: 874},
  {label:'Banstead',value: 202},
  {label:'Banstead',value: 324},
  {label:'Barbican',value: 732},
  {label:'Barnet',value: 191},
  {label:'Barry',value: 688},
  {label:'BASINGSTOKE',value: 582},
  {label:'Bath',value: 193},
  {label:'BATTERSEA NINE ELMS',value: 598},
  {label:'Battersea',value: 737},
  {label:'Bayswater Temp',value: 579},
  {label:'Bayswater',value: 756},
  {label:'Beaconsfield',value: 177},
  {label:'Beckenham',value: 212},
  {label:'Bedford',value: 725},
  {label:'Belgravia',value: 665},
  {label:'Berkhamsted',value: 223},
  {label:'Biggin Hill',value: 240},
  {label:'Billericay',value: 229},
  {label:'Birch Hill',value: 159},
  {label:'Bishop s Stortford',value: 101},
  {label:'Blaby',value: 141},
  {label:'Bloomsbury',value: 207},
  {label:'Brackley',value: 797},
  {label:'Bracknell',value: 706},
  {label:'Brent Cross',value: 119},
  {label:'Bridport',value: 475},
  {label:'Brighton',value: 114},
  {label:'Bromley South',value: 224},
  {label:'Bromley',value: 158},
  {label:'Bromsgrove',value: 877},
  {label:'Broxbourne',value: 575},
  {label:'Buckhurst Hill',value: 102},
  {label:'Buckingham',value: 769},
  {label:'Burgess Hill',value: 123},
  {label:'Burgh Heath',value: 567},
  {label:'Burnt Common',value: 571},
  {label:'Bury St Edmunds',value: 140},
  {label:'Buxton',value: 748},
  {label:'Byres Road',value: 308},
  {label:'Caldicot',value: 476},
  {label:'Cambridge',value: 651},
  {label:'Camden',value: 536},
  {label:'Canary Wharf',value: 664},
  {label:'Canterbury',value: 533},
  {label:'Cardiff Queen Street',value: 501},
  {label:'Caterham',value: 178},
  {label:'Caversham',value: 184},
  {label:'Chandlers Ford',value: 668},
  {label:'Cheadle Hulme',value: 710},
  {label:'Cheam',value: 559},
  {label:'Cheltenham',value: 663},
  {label:'Chesham',value: 192},
  {label:'Chester',value: 842},
  {label:'Chichester',value: 208},
  {label:'Chippenham',value: 523},
  {label:'Chipping Sodbury',value: 751},
  {label:'Chiswick',value: 760},
  {label:'Christchurch',value: 754},
  {label:'Cirencester',value: 220},
  {label:'Clapham Common',value: 616},
  {label:'Clapham Junction',value: 767},
  {label:'Clerkenwell',value: 492},
  {label:'Clifton',value: 834},
  {label:'Cobham',value: 176},
  {label:'Colchester',value: 455},
  {label:'Colmore Row (Birmingham)',value: 742},
  {label:'Comely Bank',value: 750},
  {label:'Coulsdon DFC',value: 513},
  {label:'Coulsdon',value: 129},
  {label:'Cowbridge',value: 735},
  {label:'Crewkerne',value: 458},
  {label:'Crouch End',value: 835},
  {label:'Crowborough',value: 110},
  {label:'Croydon',value: 477},
  {label:'Dartford',value: 693},
  {label:'Daventry',value: 156},
  {label:'Dibden',value: 118},
  {label:'Dorchester',value: 120},
  {label:'Dorking',value: 107},
  {label:'Dorking',value: 527},
  {label:'Dorking',value: 755},
  {label:'Droitwich',value: 672},
  {label:'Durham',value: 730},
  {label:'Ealing',value: 586},
  {label:'East Cowes',value: 313},
  {label:'East Grinstead',value: 741},
  {label:'East Putney',value: 820},
  {label:'East Sheen',value: 149},
  {label:'Eastbourne',value: 757},
  {label:'Edenbridge',value: 556},
  {label:'Edgware Road',value: 768},
  {label:'Egham',value: 519},
  {label:'Eldon Square',value: 461},
  {label:'Ely',value: 205},
  {label:'Enfield CFC',value: 199},
  {label:'Enfield Chase',value: 521},
  {label:'Enfield',value: 179},
  {label:'Epsom',value: 104},
  {label:'Esher',value: 121},
  {label:'Evesham',value: 303},
  {label:'Evington',value: 136},
  {label:'Exeter',value: 702},
  {label:'Faringdon',value: 871},
  {label:'Farnham',value: 692},
  {label:'Finchley Central',value: 876},
  {label:'Finchley',value: 215},
  {label:'Fitzroy Street',value: 552},
  {label:'Fleet',value: 196},
  {label:'Foregate Street',value: 615},
  {label:'Formby',value: 749},
  {label:'Four Oaks',value: 150},
  {label:'Frimley',value: 652},
  {label:'Fulham Palace Road',value: 530},
  {label:'Fulham',value: 681},
  {label:'Gerrards Cross',value: 459},
  {label:'Gillingham',value: 105},
  {label:'Gloucester Road',value: 230},
  {label:'Godalming',value: 216},
  {label:'Goldsworth Park',value: 181},
  {label:'Gosport',value: 152},
  {label:'Great Malvern',value: 237},
  {label:'Green Street Green',value: 165},
  {label:'Greenford CFC',value: 259},
  {label:'Greenwich',value: 740},
  {label:'Guildford Worplesdon Road',value: 808},
  {label:'Guildford',value: 589},
  {label:'Hailsham',value: 653},
  {label:'Hall Green',value: 122},
  {label:'Hampton',value: 612},
  {label:'Harborne',value: 796},
  {label:'Harpenden',value: 183},
  {label:'Harrogate',value: 684},
  {label:'Harrow Weald',value: 143},
  {label:'Haslemere',value: 478},
  {label:'Havant',value: 171},
  {label:'Hawkhurst',value: 529},
  {label:'Haywards Heath',value: 873},
  {label:'Hazlemere',value: 584},
  {label:'Headington - London Road',value: 806},
  {label:'Headington',value: 479},
  {label:'Heathfield',value: 595},
  {label:'Helensburgh',value: 771},
  {label:'Henley',value: 214},
  {label:'Hereford',value: 507},
  {label:'Hersham',value: 765},
  {label:'Hertford',value: 175},
  {label:'Hexham',value: 782},
  {label:'High Holborn',value: 601},
  {label:'High Wycombe',value: 607},
  {label:'Highbury Corner',value: 637},
  {label:'Hitchin',value: 685},
  {label:'Holloway Road',value: 112},
  {label:'Holsworthy',value: 480},
  {label:'Horley - Brighton Road',value: 802},
  {label:'Horley',value: 233},
  {label:'Hornchurch',value: 555},
  {label:'Horsham New',value: 580},
  {label:'Horsham',value: 200},
  {label:'Hove',value: 605},
  {label:'Huntingdon',value: 163},
  {label:'Hythe',value: 654},
  {label:'Ipswich (Corn Exchange)',value: 743},
  {label:'Ipswich',value: 632},
  {label:'Islington',value: 780},
  {label:'Jesmond',value: 520},
  {label:'JL Foodhall Bluewater',value: 493},
  {label:'JL Foodhall Oxford Street',value: 456},
  {label:'John Barnes',value: 174},
  {label:'Kenilworth',value: 460},
  {label:'Kensington Gardens',value: 535},
  {label:'Kensington',value: 678},
  {label:'Keynsham',value: 557},
  {label:'Kings Cross Station',value: 619},
  {label:'Kings Cross',value: 590},
  {label:'Kings Hill',value: 744},
  {label:'Kings Road',value: 173},
  {label:'Kingsthorpe',value: 148},
  {label:'Kingston',value: 195},
  {label:'Knightsbridge',value: 641},
  {label:'Knutsford',value: 326},
  {label:'Leatherhead',value: 859},
  {label:'Leeds',value: 574},
  {label:'Leek',value: 606},
  {label:'Leigh On Sea',value: 481},
  {label:'Leighton Buzzard',value: 154},
  {label:'Lewes',value: 727},
  {label:'Lichfield',value: 699},
  {label:'Lincoln',value: 694},
  {label:'Little Waitrose at John Lewis Watford',value: 781},
  {label:'Little Waitrose John Lewis Southampton',value: 815},
  {label:'Littlehampton',value: 505},
  {label:'Locks Heath',value: 563},
  {label:'Longfield',value: 109},
  {label:'Lutterworth',value: 487},
  {label:'Lymington New',value: 798},
  {label:'Maidenhead',value: 194},
  {label:'Malmesbury',value: 511},
  {label:'Manchester Piccadilly',value: 636},
  {label:'Market Harborough',value: 728},
  {label:'Marlborough',value: 164},
  {label:'Marlow',value: 146},
  {label:'Marlow',value: 465},
  {label:'Marylebone',value: 236},
  {label:'Meanwood',value: 828},
  {label:'Melksham',value: 319},
  {label:'Menai Bridge',value: 318},
  {label:'Mill Hill',value: 670},
  {label:'Milngavie',value: 630},
  {label:'Milton Keynes',value: 115},
  {label:'Monmouth',value: 217},
  {label:'Monument',value: 773},
  {label:'Morningside',value: 761},
  {label:'MOUNTSORREL',value: 403},
  {label:'Muswell Hill',value: 639},
  {label:'Nailsea',value: 515},
  {label:'New Malden',value: 131},
  {label:'Newark',value: 227},
  {label:'Newbury',value: 676},
  {label:'Newmarket',value: 674},
  {label:'Newport',value: 687},
  {label:'Newton Mearns',value: 327},
  {label:'North Walsham',value: 622},
  {label:'Northwich',value: 759},
  {label:'Northwood',value: 186},
  {label:'Norwich',value: 222},
  {label:'Notting Hill Gate',value: 644},
  {label:'Oadby',value: 847},
  {label:'Oakgrove',value: 752},
  {label:'Okehampton',value: 234},
  {label:'Old Brompton Road',value: 583},
  {label:'Otley',value: 691},
  {label:'Oundle',value: 758},
  {label:'Oxford Botley Road',value: 581},
  {label:'Oxted',value: 838},
  {label:'Paddock Wood',value: 655},
  {label:'Palmers Green',value: 588},
  {label:'Parkstone',value: 766},
  {label:'Parsons Green',value: 516},
  {label:'Peterborough',value: 103},
  {label:'Peterborough',value: 531},
  {label:'Petersfield',value: 209},
  {label:'Petts Wood',value: 568},
  {label:'Pimlico',value: 614},
  {label:'Ponteland',value: 482},
  {label:'Pontprennau',value: 457},
  {label:'Portishead',value: 669},
  {label:'Portman Square',value: 569},
  {label:'Poundbury',value: 733},
  {label:'Poynton',value: 312},
  {label:'Putney',value: 225},
  {label:'Ramsgate',value: 160},
  {label:'Raynes Park',value: 846},
  {label:'Reading',value: 218},
  {label:'Red Houses (Jersey)',value: 336},
  {label:'Richmond',value: 188},
  {label:'Rickmansworth',value: 698},
  {label:'Ringwood',value: 203},
  {label:'ROEHAMPTON',value: 736},
  {label:'Rohais (Guernsey)',value: 333},
  {label:'Romsey',value: 671},
  {label:'Ruislip',value: 197},
  {label:'Rushden',value: 690},
  {label:'Rustington',value: 596},
  {label:'Saffron Walden',value: 135},
  {label:'Salisbury',value: 226},
  {label:'Saltash',value: 656},
  {label:'Sandbach',value: 680},
  {label:'Sanderstead',value: 677},
  {label:'Sandhurst',value: 799},
  {label:'Saxmundham',value: 483},
  {label:'Sceptre (Watford)',value: 534},
  {label:'Sevenoaks',value: 182},
  {label:'Sevenoaks',value: 464},
  {label:'Sheffield',value: 695},
  {label:'Sherborne',value: 604},
  {label:'Shrewsbury',value: 525},
  {label:'Sidcup',value: 643},
  {label:'Sidmouth',value: 657},
  {label:'SKY (OSTERLEY)',value: 865},
  {label:'Solihull',value: 642},
  {label:'South Bank Tower',value: 703},
  {label:'South Harrow',value: 219},
  {label:'South Woodford',value: 231},
  {label:'Southampton New',value: 720},
  {label:'Southend',value: 213},
  {label:'Southsea',value: 170},
  {label:'Spinningfields',value: 558},
  {label:'St Albans',value: 166},
  {label:'St Helier (Jersey)',value: 334},
  {label:'St Ives',value: 108},
  {label:'St Katharine Docks',value: 753},
  {label:'St Neots',value: 185},
  {label:'St Saviour (Jersey)',value: 332},
  {label:'Staines',value: 235},
  {label:'Stamford',value: 484},
  {label:'Stevenage',value: 167},
  {label:'Stirling',value: 620},
  {label:'Storrington',value: 317},
  {label:'Stourbridge',value: 155},
  {label:'Stratford City',value: 328},
  {label:'Stratford Upon Avon',value: 708},
  {label:'Stroud',value: 210},
  {label:'Sudbury',value: 658},
  {label:'Sunningdale',value: 190},
  {label:'Surbiton',value: 232},
  {label:'Sutton Coldfield',value: 522},
  {label:'Swaffham',value: 686},
  {label:'Swindon',value: 504},
  {label:'Teignmouth',value: 554},
  {label:'Temple Fortune',value: 125},
  {label:'Tenterden',value: 201},
  {label:'Thame',value: 206},
  {label:'Thatcham',value: 659},
  {label:'Tonbridge',value: 667},
  {label:'Torquay',value: 485},
  {label:'Tottenham Court Road',value: 526},
  {label:'Towcester',value: 682},
  {label:'Trinity Square',value: 833},
  {label:'Truro',value: 648},
  {label:'Tubs Hill',value: 739},
  {label:'Twickenham',value: 660},
  {label:'Twyford',value: 238},
  {label:'Uckfield',value: 506},
  {label:'Upminster',value: 486},
  {label:'UTTOXETER',value: 599},
  {label:'Vauxhall',value: 789},
  {label:'Victoria Bressenden Place',value: 860},
  {label:'Victoria Street',value: 783},
  {label:'Walbrook',value: 573},
  {label:'Wallingford',value: 675},
  {label:'Walton-le-Dale',value: 721},
  {label:'Walton-on-Thames',value: 562},
  {label:'Wandsworth',value: 673},
  {label:'Wantage',value: 153},
  {label:'Warminster',value: 701},
  {label:'Waterlooville',value: 239},
  {label:'Wellington',value: 315},
  {label:'Wells',value: 729},
  {label:'Welwyn Garden City',value: 204},
  {label:'West Byfleet',value: 189},
  {label:'West Ealing',value: 764},
  {label:'West Hampstead',value: 524},
  {label:'West Kensington',value: 587},
  {label:'Westbury Park',value: 151},
  {label:'Westfield London',value: 462},
  {label:'Weston Super Mare',value: 309},
  {label:'Weybridge',value: 157},
  {label:'Whetstone',value: 124},
  {label:'Willerby',value: 697},
  {label:'Wilmslow',value: 711},
  {label:'Wimbledon Hill',value: 528},
  {label:'Wimbledon',value: 314},
  {label:'Wimborne',value: 805},
  {label:'Winchester',value: 463},
  {label:'Winchmore Hill',value: 878},
  {label:'Windsor New',value: 772},
  {label:'Winton',value: 161},
  {label:'Witney',value: 142},
  {label:'Wokingham',value: 221},
  {label:'Wolverhampton',value: 696},
  {label:'Woodley',value: 180},
  {label:'Wootton',value: 726},
  {label:'Worcester Park',value: 661},
  {label:'Worcester',value: 700},
  {label:'Worthing',value: 689},
  {label:'Wymondham',value: 662},
  {label:'Yateley',value: 198},
  {label:'York',value: 311},
];

const Countries_List = [
  {label:'Abergavenny',value: 683},
  {label:'Abingdon',value: 211},
  {label:'Acton',value: 502},
  {label:'Addlestone',value: 542},
  {label:'Admiral Park (Guernsey)',value: 335},
  {label:'Alcester',value: 474},
  {label:'Alderley Edge',value: 560},
  {label:'Alderley Old',value: 602},
  {label:'Allington Park',value: 137},
  {label:'Alton',value: 329},
  {label:'Altrincham',value: 494},
  {label:'Amersham',value: 578},
  {label:'Ampthill',value: 722},
  {label:'Andover',value: 168},
  {label:'Ashbourne',value: 316},
  {label:'Ashford',value: 705},
  {label:'Aylesbury',value: 625},
  {label:'Bagshot Road',value: 738},
  {label:'Bagshot',value: 514},
  {label:'Balham',value: 719},
  {label:'Banbury',value: 874},
  {label:'Banstead',value: 202},
  {label:'Banstead',value: 324},
  {label:'Barbican',value: 732},
  {label:'Barnet',value: 191},
  {label:'Barry',value: 688},
  {label:'BASINGSTOKE',value: 582},
  {label:'Bath',value: 193},
  {label:'BATTERSEA NINE ELMS',value: 598},
  {label:'Battersea',value: 737},
  {label:'Bayswater Temp',value: 579},
  {label:'Bayswater',value: 756},
  {label:'Beaconsfield',value: 177},
  {label:'Beckenham',value: 212},
  {label:'Bedford',value: 725},
  {label:'Belgravia',value: 665},
  {label:'Berkhamsted',value: 223},
  {label:'Biggin Hill',value: 240},
  {label:'Billericay',value: 229},
  {label:'Birch Hill',value: 159},
  {label:'Bishop s Stortford',value: 101},
  {label:'Blaby',value: 141},
  {label:'Bloomsbury',value: 207},
  {label:'Brackley',value: 797},
  {label:'Bracknell',value: 706},
  {label:'Brent Cross',value: 119},
  {label:'Bridport',value: 475},
  {label:'Brighton',value: 114},
  {label:'Bromley South',value: 224},
  {label:'Bromley',value: 158},
  {label:'Bromsgrove',value: 877},
  {label:'Broxbourne',value: 575},
  {label:'Buckhurst Hill',value: 102},
  {label:'Buckingham',value: 769},
  {label:'Burgess Hill',value: 123},
  {label:'Burgh Heath',value: 567},
  {label:'Burnt Common',value: 571},
  {label:'Bury St Edmunds',value: 140},
  {label:'Buxton',value: 748},
  {label:'Byres Road',value: 308},
  {label:'Caldicot',value: 476},
  {label:'Cambridge',value: 651},
  {label:'Camden',value: 536},
  {label:'Canary Wharf',value: 664},
  {label:'Canterbury',value: 533},
  {label:'Cardiff Queen Street',value: 501},
  {label:'Caterham',value: 178},
  {label:'Caversham',value: 184},
  {label:'Chandlers Ford',value: 668},
  {label:'Cheadle Hulme',value: 710},
  {label:'Cheam',value: 559},
  {label:'Cheltenham',value: 663},
  {label:'Chesham',value: 192},
  {label:'Chester',value: 842},
  {label:'Chichester',value: 208},
  {label:'Chippenham',value: 523},
  {label:'Chipping Sodbury',value: 751},
  {label:'Chiswick',value: 760},
  {label:'Christchurch',value: 754},
  {label:'Cirencester',value: 220},
  {label:'Clapham Common',value: 616},
  {label:'Clapham Junction',value: 767},
  {label:'Clerkenwell',value: 492},
  {label:'Clifton',value: 834},
  {label:'Cobham',value: 176},
  {label:'Colchester',value: 455},
  {label:'Colmore Row (Birmingham)',value: 742},
  {label:'Comely Bank',value: 750},
  {label:'Coulsdon DFC',value: 513},
  {label:'Coulsdon',value: 129},
  {label:'Cowbridge',value: 735},
  {label:'Crewkerne',value: 458},
  {label:'Crouch End',value: 835},
  {label:'Crowborough',value: 110},
  {label:'Croydon',value: 477},
  {label:'Dartford',value: 693},
  {label:'Daventry',value: 156},
  {label:'Dibden',value: 118},
  {label:'Dorchester',value: 120},
  {label:'Dorking',value: 107},
  {label:'Dorking',value: 527},
  {label:'Dorking',value: 755},
  {label:'Droitwich',value: 672},
  {label:'Durham',value: 730},
  {label:'Ealing',value: 586},
  {label:'East Cowes',value: 313},
  {label:'East Grinstead',value: 741},
  {label:'East Putney',value: 820},
  {label:'East Sheen',value: 149},
  {label:'Eastbourne',value: 757},
  {label:'Edenbridge',value: 556},
  {label:'Edgware Road',value: 768},
  {label:'Egham',value: 519},
  {label:'Eldon Square',value: 461},
  {label:'Ely',value: 205},
  {label:'Enfield CFC',value: 199},
  {label:'Enfield Chase',value: 521},
  {label:'Enfield',value: 179},
  {label:'Epsom',value: 104},
  {label:'Esher',value: 121},
  {label:'Evesham',value: 303},
  {label:'Evington',value: 136},
  {label:'Exeter',value: 702},
  {label:'Faringdon',value: 871},
  {label:'Farnham',value: 692},
  {label:'Finchley Central',value: 876},
  {label:'Finchley',value: 215},
  {label:'Fitzroy Street',value: 552},
  {label:'Fleet',value: 196},
  {label:'Foregate Street',value: 615},
  {label:'Formby',value: 749},
  {label:'Four Oaks',value: 150},
  {label:'Frimley',value: 652},
  {label:'Fulham Palace Road',value: 530},
  {label:'Fulham',value: 681},
  {label:'Gerrards Cross',value: 459},
  {label:'Gillingham',value: 105},
  {label:'Gloucester Road',value: 230},
  {label:'Godalming',value: 216},
  {label:'Goldsworth Park',value: 181},
  {label:'Gosport',value: 152},
  {label:'Great Malvern',value: 237},
  {label:'Green Street Green',value: 165},
  {label:'Greenford CFC',value: 259},
  {label:'Greenwich',value: 740},
  {label:'Guildford Worplesdon Road',value: 808},
  {label:'Guildford',value: 589},
  {label:'Hailsham',value: 653},
  {label:'Hall Green',value: 122},
  {label:'Hampton',value: 612},
  {label:'Harborne',value: 796},
  {label:'Harpenden',value: 183},
  {label:'Harrogate',value: 684},
  {label:'Harrow Weald',value: 143},
  {label:'Haslemere',value: 478},
  {label:'Havant',value: 171},
  {label:'Hawkhurst',value: 529},
  {label:'Haywards Heath',value: 873},
  {label:'Hazlemere',value: 584},
  {label:'Headington - London Road',value: 806},
  {label:'Headington',value: 479},
  {label:'Heathfield',value: 595},
  {label:'Helensburgh',value: 771},
  {label:'Henley',value: 214},
  {label:'Hereford',value: 507},
  {label:'Hersham',value: 765},
  {label:'Hertford',value: 175},
  {label:'Hexham',value: 782},
  {label:'High Holborn',value: 601},
  {label:'High Wycombe',value: 607},
  {label:'Highbury Corner',value: 637},
  {label:'Hitchin',value: 685},
  {label:'Holloway Road',value: 112},
  {label:'Holsworthy',value: 480},
  {label:'Horley - Brighton Road',value: 802},
  {label:'Horley',value: 233},
  {label:'Hornchurch',value: 555},
  {label:'Horsham New',value: 580},
  {label:'Horsham',value: 200},
  {label:'Hove',value: 605},
  {label:'Huntingdon',value: 163},
  {label:'Hythe',value: 654},
  {label:'Ipswich (Corn Exchange)',value: 743},
  {label:'Ipswich',value: 632},
  {label:'Islington',value: 780},
  {label:'Jesmond',value: 520},
  {label:'JL Foodhall Bluewater',value: 493},
  {label:'JL Foodhall Oxford Street',value: 456},
  {label:'John Barnes',value: 174},
  {label:'Kenilworth',value: 460},
  {label:'Kensington Gardens',value: 535},
  {label:'Kensington',value: 678},
  {label:'Keynsham',value: 557},
  {label:'Kings Cross Station',value: 619},
  {label:'Kings Cross',value: 590},
  {label:'Kings Hill',value: 744},
  {label:'Kings Road',value: 173},
  {label:'Kingsthorpe',value: 148},
  {label:'Kingston',value: 195},
  {label:'Knightsbridge',value: 641},
  {label:'Knutsford',value: 326},
  {label:'Leatherhead',value: 859},
  {label:'Leeds',value: 574},
  {label:'Leek',value: 606},
  {label:'Leigh On Sea',value: 481},
  {label:'Leighton Buzzard',value: 154},
  {label:'Lewes',value: 727},
  {label:'Lichfield',value: 699},
  {label:'Lincoln',value: 694},
  {label:'Little Waitrose at John Lewis Watford',value: 781},
  {label:'Little Waitrose John Lewis Southampton',value: 815},
  {label:'Littlehampton',value: 505},
  {label:'Locks Heath',value: 563},
  {label:'Longfield',value: 109},
  {label:'Lutterworth',value: 487},
  {label:'Lymington New',value: 798},
  {label:'Maidenhead',value: 194},
  {label:'Malmesbury',value: 511},
  {label:'Manchester Piccadilly',value: 636},
  {label:'Market Harborough',value: 728},
  {label:'Marlborough',value: 164},
  {label:'Marlow',value: 146},
  {label:'Marlow',value: 465},
  {label:'Marylebone',value: 236},
  {label:'Meanwood',value: 828},
  {label:'Melksham',value: 319},
  {label:'Menai Bridge',value: 318},
  {label:'Mill Hill',value: 670},
  {label:'Milngavie',value: 630},
  {label:'Milton Keynes',value: 115},
  {label:'Monmouth',value: 217},
  {label:'Monument',value: 773},
  {label:'Morningside',value: 761},
  {label:'MOUNTSORREL',value: 403},
  {label:'Muswell Hill',value: 639},
  {label:'Nailsea',value: 515},
  {label:'New Malden',value: 131},
  {label:'Newark',value: 227},
  {label:'Newbury',value: 676},
  {label:'Newmarket',value: 674},
  {label:'Newport',value: 687},
  {label:'Newton Mearns',value: 327},
  {label:'North Walsham',value: 622},
  {label:'Northwich',value: 759},
  {label:'Northwood',value: 186},
  {label:'Norwich',value: 222},
  {label:'Notting Hill Gate',value: 644},
  {label:'Oadby',value: 847},
  {label:'Oakgrove',value: 752},
  {label:'Okehampton',value: 234},
  {label:'Old Brompton Road',value: 583},
  {label:'Otley',value: 691},
  {label:'Oundle',value: 758},
  {label:'Oxford Botley Road',value: 581},
  {label:'Oxted',value: 838},
  {label:'Paddock Wood',value: 655},
  {label:'Palmers Green',value: 588},
  {label:'Parkstone',value: 766},
  {label:'Parsons Green',value: 516},
  {label:'Peterborough',value: 103},
  {label:'Peterborough',value: 531},
  {label:'Petersfield',value: 209},
  {label:'Petts Wood',value: 568},
  {label:'Pimlico',value: 614},
  {label:'Ponteland',value: 482},
  {label:'Pontprennau',value: 457},
  {label:'Portishead',value: 669},
  {label:'Portman Square',value: 569},
  {label:'Poundbury',value: 733},
  {label:'Poynton',value: 312},
  {label:'Putney',value: 225},
  {label:'Ramsgate',value: 160},
  {label:'Raynes Park',value: 846},
  {label:'Reading',value: 218},
  {label:'Red Houses (Jersey)',value: 336},
  {label:'Richmond',value: 188},
  {label:'Rickmansworth',value: 698},
  {label:'Ringwood',value: 203},
  {label:'ROEHAMPTON',value: 736},
  {label:'Rohais (Guernsey)',value: 333},
  {label:'Romsey',value: 671},
  {label:'Ruislip',value: 197},
  {label:'Rushden',value: 690},
  {label:'Rustington',value: 596},
  {label:'Saffron Walden',value: 135},
  {label:'Salisbury',value: 226},
  {label:'Saltash',value: 656},
  {label:'Sandbach',value: 680},
  {label:'Sanderstead',value: 677},
  {label:'Sandhurst',value: 799},
  {label:'Saxmundham',value: 483},
  {label:'Sceptre (Watford)',value: 534},
  {label:'Sevenoaks',value: 182},
  {label:'Sevenoaks',value: 464},
  {label:'Sheffield',value: 695},
  {label:'Sherborne',value: 604},
  {label:'Shrewsbury',value: 525},
  {label:'Sidcup',value: 643},
  {label:'Sidmouth',value: 657},
  {label:'SKY (OSTERLEY)',value: 865},
  {label:'Solihull',value: 642},
  {label:'South Bank Tower',value: 703},
  {label:'South Harrow',value: 219},
  {label:'South Woodford',value: 231},
  {label:'Southampton New',value: 720},
  {label:'Southend',value: 213},
  {label:'Southsea',value: 170},
  {label:'Spinningfields',value: 558},
  {label:'St Albans',value: 166},
  {label:'St Helier (Jersey)',value: 334},
  {label:'St Ives',value: 108},
  {label:'St Katharine Docks',value: 753},
  {label:'St Neots',value: 185},
  {label:'St Saviour (Jersey)',value: 332},
  {label:'Staines',value: 235},
  {label:'Stamford',value: 484},
  {label:'Stevenage',value: 167},
  {label:'Stirling',value: 620},
  {label:'Storrington',value: 317},
  {label:'Stourbridge',value: 155},
  {label:'Stratford City',value: 328},
  {label:'Stratford Upon Avon',value: 708},
  {label:'Stroud',value: 210},
  {label:'Sudbury',value: 658},
  {label:'Sunningdale',value: 190},
  {label:'Surbiton',value: 232},
  {label:'Sutton Coldfield',value: 522},
  {label:'Swaffham',value: 686},
  {label:'Swindon',value: 504},
  {label:'Teignmouth',value: 554},
  {label:'Temple Fortune',value: 125},
  {label:'Tenterden',value: 201},
  {label:'Thame',value: 206},
  {label:'Thatcham',value: 659},
  {label:'Tonbridge',value: 667},
  {label:'Torquay',value: 485},
  {label:'Tottenham Court Road',value: 526},
  {label:'Towcester',value: 682},
  {label:'Trinity Square',value: 833},
  {label:'Truro',value: 648},
  {label:'Tubs Hill',value: 739},
  {label:'Twickenham',value: 660},
  {label:'Twyford',value: 238},
  {label:'Uckfield',value: 506},
  {label:'Upminster',value: 486},
  {label:'UTTOXETER',value: 599},
  {label:'Vauxhall',value: 789},
  {label:'Victoria Bressenden Place',value: 860},
  {label:'Victoria Street',value: 783},
  {label:'Walbrook',value: 573},
  {label:'Wallingford',value: 675},
  {label:'Walton-le-Dale',value: 721},
  {label:'Walton-on-Thames',value: 562},
  {label:'Wandsworth',value: 673},
  {label:'Wantage',value: 153},
  {label:'Warminster',value: 701},
  {label:'Waterlooville',value: 239},
  {label:'Wellington',value: 315},
  {label:'Wells',value: 729},
  {label:'Welwyn Garden City',value: 204},
  {label:'West Byfleet',value: 189},
  {label:'West Ealing',value: 764},
  {label:'West Hampstead',value: 524},
  {label:'West Kensington',value: 587},
  {label:'Westbury Park',value: 151},
  {label:'Westfield London',value: 462},
  {label:'Weston Super Mare',value: 309},
  {label:'Weybridge',value: 157},
  {label:'Whetstone',value: 124},
  {label:'Willerby',value: 697},
  {label:'Wilmslow',value: 711},
  {label:'Wimbledon Hill',value: 528},
  {label:'Wimbledon',value: 314},
  {label:'Wimborne',value: 805},
  {label:'Winchester',value: 463},
  {label:'Winchmore Hill',value: 878},
  {label:'Windsor New',value: 772},
  {label:'Winton',value: 161},
  {label:'Witney',value: 142},
  {label:'Wokingham',value: 221},
  {label:'Wollaton',value: 591},
  {label:'Wolverhampton',value: 696},
  {label:'Woodley',value: 180},
  {label:'Wootton',value: 726},
  {label:'Worcester Park',value: 661},
  {label:'Worcester',value: 700},
  {label:'Worthing',value: 689},
  {label:'Wymondham',value: 662},
  {label:'Yateley',value: 198},
  {label:'York',value: 311},
];

export default function AddBranches() {

  const [selectedValue, setSelectedValue] = useState(Countries_List)

  const postAllBranchesData = () => {
    const branches = ['Peterborough', 'christmas']
    const requestOptions = {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      // body: '{"data" : ' + json + '}'
      body: JSON.stringify({ data: selectedValue })
      };
      fetch('/postbranches', requestOptions)
      .then((response) => {
        response.json()
        NotificationManager.success('Success message', 'Branches Selected');
      }).catch((err) => {
        NotificationManager.error('Failure message', 'Failed to Add Branches');
      })
      // .then(data => this.setState({ postId: data.id }));
  }

  return(
    <div className="container" style={{padding : '10px 50px 10px 50px'}}>
      <div className="row">
        <div className="col-md-6"></div>
        <div className="col-md-12">
          <CreatableSelect options={Countries} components={animatedComponents} styles={{  option: (provided) => ({
              ...provided,
              color: 'black',
              fontSize: '15px'
            }),}}
            onChange={(option) => {
              option !== "All" ? setSelectedValue(option) : setSelectedValue(Countries_List)
            }}
            defaultValue = {Countries[0]}
            isMulti />
        </div>
        <div className="col-md-6" style={{ padding : '10px 10px 0px 10px'}}><button onClick={postAllBranchesData} variant="contained" class='keyword'>Pick Branches</button></div>
      </div>
    </div>
  )

}
